version: '3.8'

services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - Jwt__Secret=your-super-secret-jwt
      - Jwt__Issuer=user-service
      - Jwt__Audience=notification-system
      - DB_HOST=${USER_DB_HOST}
      - DB_PORT=${USER_DB_PORT}
      - DB_NAME=${USER_DB_NAME}
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASS}

      - ConnectionStrings__DefaultConnection=Host=${USER_DB_HOST};Port=${USER_DB_PORT};Database=${USER_DB_NAME};Username=${USER_DB_USER};Password=${USER_DB_PASS}
      - ConnectionStrings__Redis=${REDIS_HOST}:${REDIS_PORT}

      - Jwt__Secret=${JWT_SECRET_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - postgres
      - redis
    networks:
      - notification_network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: user_service_postgres
    environment:
      - POSTGRES_DB=UserServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=damimola
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notification_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: user_service_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - notification_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  notification_network:
    driver: bridge
